name: Build & Deploy Dashboard

on:
  schedule:
    - cron: "*/30 * * * *"     # every 30 minutes; adjust as you prefer
  workflow_dispatch:
  push:
    paths:
      - "scripts/**"
      - ".github/workflows/site.yml"
      - "requirements.txt"

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build data.json
        run: |
          python scripts/fetch_feeds.py

      - name: Commit updated data.json (if changed)
        run: |
          if [[ -n "$(git status --porcelain dashboard/data.json)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add dashboard/data.json
            git commit -m "Update dashboard/data.json [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi

      # ---- GitHub Pages deploy (static site from repository) ----
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./dashboard"
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
